@HookTray.Api_HostAddress = http://localhost:5221

### Create a hook session
POST {{HookTray.Api_HostAddress}}/api/hooks
Accept: application/json

### Check health
GET {{HookTray.Api_HostAddress}}/health
Accept: application/json
